apiVersion: batch/v1
kind: CronJob
metadata:
  name: heartbeat
  namespace: dev
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: heartbeat
            image: busybox
            command:
            - sh
            - -c
            - echo "Heartbeat OK - $(date)"
