apiVersion: batch/v1
kind: Job
metadata:
  name: db-check
  namespace: dev
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-check
        image: postgres:15
        command:
        - sh
        - -c
        - |
          psql -h postgres-0.postgres-headless.dev.svc.cluster.local -U postgres -c "CREATE DATABASE mydb;" &&
          psql -h postgres-0.postgres-headless.dev.svc.cluster.local -U postgres -d mydb -c "CREATE TABLE employees (id SERIAL PRIMARY KEY, name VARCHAR(100), salary INT);" &&
          psql -h postgres-0.postgres-headless.dev.svc.cluster.local -U postgres -d mydb -c "\dt"
        env:
        - name: PGPASSWORD
          value: "mypassword"
