apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-sa                               #name SA
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader                                  #name ROLE
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding                           #NAME ROLBIND
  namespace: dev
subjects:
- kind: ServiceAccount
  name: pod-reader-sa                                #NAME SA IN BINDING
  namespace: dev
roleRef:
  kind: Role
  name: pod-reader                                   #NAME ROLE IN BINDING
  apiGroup: rbac.authorization.k8s.io

---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-reader-binding
subjects:
- kind: ServiceAccount
  name: pod-reader-sa
  namespace: dev
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
